/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudwithjava;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP Nav
 */
public class LoginPage extends javax.swing.JFrame {
    StudentModel sd = new StudentModel();
    int id;
    Boolean isUpdate = false;
    SingletonClass singletonClass = SingletonClass.getInstance();

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        delete.setVisible(false);
       
    }
    public LoginPage(int id){
         initComponents();
         jButton1.setText("Update");
         isUpdate = true;
         
        
        String update = "SELECT * FROM student WHERE id = "+id;
        try{
            PreparedStatement ps = singletonClass.connection.prepareCall(update);
            ResultSet result = ps.executeQuery();
            while(result.next()){
            sd.setId(result.getInt("id"));
            sd.setName(result.getString("name"));
            sd.setEmail(result.getString("email"));
            delete.setVisible(true);
            }
        }catch(SQLException sqlException){
        System.out.println("sqlException "+sqlException);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        email.setText("Email");

        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete)
                            .addComponent(jButton1))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(name.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Name");
        }else if(email.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Email");
        }
        else if(isUpdate == true) {
            String updateData = "UPDATE student set name=?, email=? where id=?";
            
            try{
                PreparedStatement ps = singletonClass.connection.prepareCall(updateData);
                ps.setString(1, name.getText());
                ps.setString(2, email.getText());
                ps.setInt(3,sd.getId());
                
             
                int insertData = ps.executeUpdate();
                if(insertData > 0){
                System.out.println("Update Data");
             
                SecondScreen sc = new SecondScreen();
                sc.setVisible(true);
                this.dispose();
              }
            }catch(SQLException sqlException){
                System.out.println("sqlException"+sqlException.getMessage());
            }
    }else{
            String data = "INSERT INTO student(name, email) VALUES(?,?)";
            PreparedStatement ps;
            try{
            ps = singletonClass.connection.prepareCall(data);
            ps.setString(1,name.getText().toString());
            ps.setString(2,email.getText().toString());
            
            int insertData = ps.executeUpdate();
                if(insertData > 0){
                System.out.println("Print Data");
             
                SecondScreen sc = new SecondScreen();
                sc.setVisible(true);
                this.dispose();
            }
        }
            catch(SQLException sqlException){
            System.out.println("sqlException "+sqlException.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        String deleteStudent = "DELETE FROM student where id = ?";
        PreparedStatement statement;
            try {
                statement = singletonClass.connection.prepareStatement(deleteStudent);
                statement.setInt(1, sd.getId());

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    System.out.println("A user is deleted");
                    SecondScreen secondScreen = new SecondScreen();
                    secondScreen.setVisible(true);
                    this.dispose();

                }
            } catch (SQLException sqlException) {
                System.out.println("sqlException "+sqlException.getMessage());
            }
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                  new LoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
